project:
  type: sdca-theme

website:
  # TODO: Change title and URLs to fit the name of the repo
  title: "SDCA website template"
  site-url: "https://steno-aarhus.github.io/REPO-NAME/"
  repo-url: "https://github.com/steno-aarhus/REPO-NAME"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/REPO-NAME"
        aria-label: "GitHub icon: Link to website repository"

format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss

editor: 
  markdown:
    wrap: 72
    canonical: true
